### ISSUE TITLE
Update goreleaser ldflags

### ISSUE THREAD

**Issue by jspaleta** [sensu-community/handler-plugin-template#7]
looks like we have the wrong ldflags set in the goreleaser.yml

version is not being set correctly.

**Comment by nixwiz** [comment]
Can confirm that changing
`github.com/sensu-community/sensu-plugin-sdk/version.build={{.Version}}`
to
`github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}}`
in .goreleaser.yml fixes the version problem.
